#############################################################################
#                                                                           #
#                                                                           #
#                            TOTAL OZONE RECALCULATION                      #
#                                                                           #
#                                                                           #
#        Program Name        :  ReformatDS.R                                #
#                                                                           #
#                                                                           #
#        Creation Date       :  13/07/2015                                  #
#                                                                           #
#        Last Modifications  :                                              #
#                               none                                        #
#                                                                           #
#                                                                           #
#        Author              :  SCHILL Herbert   Meteoswiss                 #
#        Modifications by    :  SCHILL Herbert                              #
#                                                                           #
#        Developing System   :  R 3.1.2    (2015)                           #
#                                                                           #
#        Short Description   :                                              #
#                                                                           #
#        'ReformatDS.R' rewrites Brewer DS-files using the recalculated     #
#        data generated by and exported from 'O3Brewer' by M. Stanek of     #
#        the CHMI.                                                          #
#                                                                           #
#        Day statistics values (mean, stadev, number of measurements) are   #
#        also written to the generated DS-file "DSjjjyy.bbb".               #
#                                                                           #
#        All necessary initial information is read from the                 #
#        ASCII-file 'ReformatDS.ini'.                                       #
#                                                                           #
#        Modification history:                                              #
#                                                                           #
#                                                                           #
#############################################################################


setwd("C:\\LKO\\Programs\\R")

source("DateZeit.R")
source("ReadDobsTables.R")
# source("TreatBrewerData.R")
require(stats)

statusOK <- 0

# Reads the path-file 'RecalcDS.pth' with the adress of the ini-file
# 'RecalcDS.ini' and reads the initialization parameters from the latter
# (Nparams designs the number of parameters to read from ini-file)

Nparams=5
iniParams = ReadIniFile(Nparams, "RecalcDS")
iniOk = iniParams[[1]][[1]]

if (iniOk)  # Continue, if ini file was properly read
{
	# Redefine ini-parameter vector

	BrewerStr  = iniParams[[2]][[2]]
	IcfFilename  = iniParams[[2]][[3]]
	InputFilename  = iniParams[[2]][[4]]
	OutputPath  = iniParams[[2]][[5]]
	len=nchar(OutputPath)
	if (substr(OutputPath,len,len+1)!="\\")  OutputPath=sprintf("%s%s",OutputPath, "\\")

	# Opens the ICF-file and reads the ETC and AbsCoeff values

	if (file.exists(IcfFilename))
	{
		Nparams=52
		inifile = file(IcfFilename,open="r")
		icfParams = array()
		for (i in 1:Nparams)
		{
			line = scan(inifile,what="character",nlines=1,quiet=TRUE)
			icfParams[i]=line[1]
		}
		iniOk=1
		close(inifile)
		iniOk = Nparams
	}
	else  # ICF-file file doesen't exist
	{
		infoFile = sprintf("%s%s%s","  File  ",IcfFilename, "  not found")
		print(infoFile)
		iniOk=0
	}

	if (iniOk)  # Continue, if desired files were properly read so far
	{
		AbsCoeffO3 = as.double(icfParams[7])
		AbsCoeffSO2 = as.double(icfParams[9])
		EtcO3 = as.integer(icfParams[10])
		EtcSO2 = as.integer(icfParams[11])

		# Opens the input-file which contains the recalculated ds-values

		if (file.exists(InputFilename))
		{
			ipf = file(InputFilename,open="r")
			iniOk = 1
		}
		else  # ICF-file file doesen't exist
		{
			infoFile = sprintf("%s%s%s","  File  ",InputFilename, "  not found")
			print(infoFile)
			iniOk=0
		}
	}  # end if iniOk

	if (iniOk)  # Continue, if desired files were properly read so far
	{
		# Initialization and read first line of input-file 

		first=1
		last=0
		n=0
		ng=0
		tempDay=0
		airmassDay=0.0
		timeM = array()
		airmass = array()
		tempM = array()
		nFilter = array()
		valSO2 = array()
		valO3 = array()
		sdevSO2 = array()
		sdevO3 = array()
		ValDay = array()
		SDevDay = array()
		ValDay[1]=0
		ValDay[2]=0
		SDevDay[1]=0
		SDevDay[2]=0

		hline = array()
		hline = scan(ipf,what="character",nlines=1,quiet=TRUE)

		# Perform lines of input-file **********************************************

		while (last<2)
		{
			# decode line: check on 'ds'

			if (last==0) typeM = hline[7]
			if (typeM=="ds")
			{
				if (last==0)
				{
					dd = as.integer(hline[3])
					mm = as.integer(hline[2])
					yy = as.integer(hline[4])
					date1=sprintf("%02d.%02d.%04d",dd,mm,yy)
				}
				if (first==1)
				{
					date0=date1
					first=0
				}
				if (last==1) last=2

				if ((date1!=date0) | (last==2))
				{
					# create DS-file

					dd = as.integer(substr(date0,1,2))
					mm = as.integer(substr(date0,4,5))
					yy = as.integer(substr(date0,7,10))
					jjj=0
					leap=0
					xDate = list(dd, mm, yy, jjj, leap)
					xDate = ConvertDate (xDate, 1)
					jjj=xDate[[4]]
					yyStr=substr(date0,9,10)
					mmStr=substr("YYYJANFEBMARAPRMAYJUNJULAUGSEPOCTNOVDEC",mm*3+1,mm*3+3)

					outFilename = sprintf("%s%03d%s.%s","DS",jjj,yyStr,BrewerStr)
					print(outFilename)
					outFilename = sprintf("%s%s",OutputPath,outFilename)
					otf = file(outFilename,open="w")

					# write header

					outl = sprintf ("%s", "Summary of Brewer direct sun measurements for ")
					outl = sprintf ("%s%s %2.2d%s%s\n\n", outl, mmStr, dd, "/", yyStr)
					cat (outl, file=otf)
					outl = sprintf ("%s", "Measurements made at Arosa LKO  with instrument # ")
					outl = sprintf ("%s%s\n", outl, BrewerStr)
					cat (outl, file=otf)
					outl = sprintf ("%s\n", "        Latitude  = 46.7828")
					cat (outl, file=otf)
					outl = sprintf ("%s\n\n", "        Longitude = -9.6754")
					cat (outl, file=otf)
					outl = sprintf ("%s", "        ETC Values    (O3/SO2) =")
					outl = sprintf ("%s%6i%s%6i\n", outl, EtcO3, "  /", EtcSO2)
					cat (outl, file=otf)
					outl = sprintf ("%s", "        O3 Absorption (O3/SO2) =")
					outl = sprintf ("%s%8.4f%s%8.4f\n\n", outl, AbsCoeffO3,"  /", AbsCoeffSO2)
					cat (outl, file=otf)
					outl = sprintf ("%s", "Type Time(gmt)  Temp  Airmass    ")
					outl = sprintf ("%s%s\n\n", outl, "Ozone    Error    SO2    Error")
					cat (outl, file=otf)

					# encode and write measurement lines

					for (i in 1:n)
					{
						outl = sprintf ("%s%2i%s%s%5i%9.3f", "ds", nFilter[i], "  ", timeM[i], tempM[i], airmass[i])
						outl = sprintf ("%s%10.1f%8.1f", outl, valO3[i], sdevO3[i])
						outl = sprintf ("%s%8.1f%8.1f\n", outl, valSO2[i], sdevSO2[i])
						cat (outl, file=otf)
					}  # end for i=1..n

					# perform statistics

					if (n>0)
					{
						airmassDay=mean(airmass)
						tempDay=as.integer(mean(tempM))
						ValDay[1] = mean(valO3)
						ValDay[2] = mean(valSO2)
						if (n>1)
						{
							SDevDay[1] = sd(valO3)
							SDevDay[2] = sd(valSO2)
							if  (SDevDay[1]>99.99)  SDevDay[1]=99.99
							if  (SDevDay[2]>99.99)  SDevDay[2]=99.99
						}

						# write statistics

						outl = sprintf ("\n%s%5i%9.3f", "   Daily means", tempDay, airmassDay)
						outl = sprintf ("%s%10.1f%16.1f\n", outl, ValDay[1], ValDay[2])
						cat (outl, file=otf)
						outl = sprintf ("%s%10.1f%16.1f\n", "   Standard deviation       ", SDevDay[1], SDevDay[2])
						cat (outl, file=otf)
						outl = sprintf ("%s%10i%s%3i\n\n", "   Number of obs            ", ng, " /", n)
						cat (outl, file=otf)
						outl = sprintf ("%s\n\n", "   Today's Ozone ETC =   9999.9  SO2 ETC =  9999.9")
						cat (outl, file=otf)
					}  # end if n>0

					# reset statistic counters and arrays

					n=0
					ng=0
					tempDay=0
					airmassDay=0.0
					timeM = array()
					airmass = array()
					tempM = array()
					nFilter = array()
					valSO2 = array()
					valO3 = array()
					sdevSO2 = array()
					sdevO3 = array()
					ValDay = array()
					SDevDay = array()
					ValDay[1]=0
					ValDay[2]=0
					SDevDay[1]=0
					SDevDay[2]=0
					date0=date1

					close(otf)  # close DS-file
				}
				else  # date1=date0
				{
					n=n+1
					timeM[n] = hline[1]
					airmass[n] = as.double(hline[5])
					tempM[n] = as.integer(hline[6])
					nFilter[n] = as.integer(hline[8])
					valSO2[n] = as.double(hline[9])
					valO3[n] = as.double(hline[10])
					sdevSO2[n] = as.double(hline[11])
					sdevO3[n] = as.double(hline[12])
					if (sdevO3[n]<=2.5) ng=ng+1
					hline = array()
					hline = scan(ipf,what="character",nlines=1,quiet=TRUE)
					if (nchar(hline[1])<7) last=1
				}  # end if date1:date0
			}  # end if typeM='ds'
			else  # if typeM<>'ds'
			{
				hline = array()
				hline = scan(ipf,what="character",nlines=1,quiet=TRUE)
				if (nchar(hline[1])<7) last=1
			}
		}  # end while

		close(ipf)  # close input-datafile

	}  # end if iniOk

}  # end if iniOk

